base_url: "https://account.grupoassistme.com.br"
seletores:
  btn_financeiro: 'role=button[name="Financeiro"]'
  link_custo_puro: 'role=link[name="Custo Puro"]'
  grid_linhas: '//*[@id="Dados"]/div/div/div[1]/div'
  grid_cabecalho: 'css=div[role="row"] >> nth=0'
  menu_mais: css=button:has(i.fas.fa-ellipsis-v)
  acao_visualizar: 'page.get_by_role("button", name="VISUALIZAR")'
  # Ajust√°veis depois que vermos o DOM real:
  filtro_busca: 'input[placeholder*="Pesquise aqui"]'
downloads_root: "./data"
